
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgresserver:5432/java_todo_db
      DB_USERNAME: postgres
      DB_PASSWORD: Batassuci123#
    depends_on:
      - postgresserver

  postgresserver:
    container_name: postgresserver
    image: postgres
    environment:
      POSTGRES_PASSWORD: Batassuci123#
      POSTGRES_DB: java_todo_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    driver: bridge
